// 围棋百科 - 核心术语数据

export interface GoTerm {
  id: string;
  term: string;          // 术语名称
  reading?: string;      // 读音/别名
  category: 'basic' | 'capture' | 'shape' | 'layout' | 'middlegame' | 'endgame' | 'special';
  categoryLabel: string;
  difficulty: 1 | 2 | 3; // 1=入门, 2=进阶, 3=高级
  shortDesc: string;     // 一句话解释（儿童友好）
  fullDesc: string;      // 详细解释
  analogy?: string;      // 生活化比喻
  tip?: string;          // 实战提示
}

export const TERM_CATEGORIES = [
  { key: 'basic', label: '基础概念', icon: '📐' },
  { key: 'capture', label: '吃子手法', icon: '⚔️' },
  { key: 'shape', label: '棋形与眼', icon: '🔲' },
  { key: 'layout', label: '布局要领', icon: '🏰' },
  { key: 'middlegame', label: '中盘战斗', icon: '🗡️' },
  { key: 'endgame', label: '官子收官', icon: '🏆' },
  { key: 'special', label: '特殊规则', icon: '✨' },
] as const;

export const GO_TERMS: GoTerm[] = [
  // ===== 基础概念 =====
  {
    id: 'qi',
    term: '气',
    reading: 'qì',
    category: 'basic',
    categoryLabel: '基础概念',
    difficulty: 1,
    shortDesc: '棋子旁边的空交叉点，就像棋子的"呼吸"',
    fullDesc: '在棋盘上，与一颗棋子紧紧相邻的空交叉点，就叫作这颗棋子的"气"。中间的棋子有4口气，边上的3口气，角落的只有2口气。两个或更多连接在一起的棋子，气会合并计算，可以有4口气以上。当一颗棋子所有的气都被堵住，它就会被提走。',
    analogy: '气就像棋子的呼吸空气，没有气就"窒息"被拿走了。连在一起的棋子就像手拉手的小朋友，可以共享呼吸！',
    tip: '下棋时要随时注意自己和对方棋子的气数，气少的棋子最危险。',
  },
  {
    id: 'ti',
    term: '提子',
    reading: 'tí zǐ',
    category: 'basic',
    categoryLabel: '基础概念',
    difficulty: 1,
    shortDesc: '把没有气的对方棋子从棋盘上拿走',
    fullDesc: '当一颗或一组棋子的所有气都被对方占据，这些棋子就失去了生存的条件，必须从棋盘上拿掉，这就叫"提子"。被提掉的棋子交给对方保管，最后用来计算胜负。提子是围棋中最基本的吃子方式。',
    analogy: '就像把被包围的小士兵俘虏了，要从战场上带走。',
    tip: '没有气的棋子必须立刻拿走，不能留在棋盘上。',
  },
  {
    id: 'dachi',
    term: '打吃',
    reading: 'dǎ chī',
    category: 'basic',
    categoryLabel: '基础概念',
    difficulty: 1,
    shortDesc: '让对方棋子只剩一口气的攻击',
    fullDesc: '当你落下一颗棋子后，使对方的一颗或一组棋子只剩下一口气，就叫"打吃"（也叫"叫吃"）。被打吃的棋子如果不在最后一口气上补一手，下一步就会被提走。',
    analogy: '就像喊了一声"将军！"，对方必须赶紧逃跑或防守。',
    tip: '打吃的方向很重要，要把对方往自己的棋子多的一边赶。',
  },
  {
    id: 'chang',
    term: '长',
    reading: 'cháng',
    category: 'basic',
    categoryLabel: '基础概念',
    difficulty: 1,
    shortDesc: '在己方棋子的直线上紧挨着延伸一步',
    fullDesc: '沿着己方棋子的方向，紧挨着再下一颗棋子，叫作"长"。"长"是最基本的逃跑方式，被打吃时，"长"出去可以增加气数。长也用于连接己方的棋子，加强自身力量。',
    analogy: '就像火车车厢一节一节接上去，或者蛇伸长身体往前走。',
    tip: '被打吃时第一步考虑的就是"长"出去逃跑。',
  },
  {
    id: 'lian',
    term: '连',
    reading: 'lián',
    category: 'basic',
    categoryLabel: '基础概念',
    difficulty: 1,
    shortDesc: '把己方分开的棋子接在一起',
    fullDesc: '使己方两颗或两组棋子通过相邻的位置连接在一起，叫作"连"。连在一起的棋子共享气，力量更强。连接是围棋中重要的防守手段，避免被对方分断攻击。',
    analogy: '就像两群小朋友手拉手变成一个大队伍，人多了力量大！',
    tip: '保持自己棋子连接，切断对方棋子，是围棋的基本作战思路。',
  },
  {
    id: 'duan',
    term: '断',
    reading: 'duàn',
    category: 'basic',
    categoryLabel: '基础概念',
    difficulty: 1,
    shortDesc: '把对方的棋子切断分开',
    fullDesc: '在对方棋子之间的空位落子，使原来连接的棋子被分开，叫作"断"。断是攻击的重要手段，被断开的棋子气数减少，力量减弱，容易被分别攻击。',
    analogy: '就像把一条绳子剪成两段，每段都没那么结实了。',
    tip: '寻找对方的断点，是发现攻击机会的好方法。',
  },
  {
    id: 'jinzhoudian',
    term: '禁着点',
    reading: 'jìn zháo diǎn',
    category: 'special',
    categoryLabel: '特殊规则',
    difficulty: 1,
    shortDesc: '不能下子的位置——下了自己的棋子就没气了',
    fullDesc: '棋盘上某个交叉点，如果一方下子后，该棋子立即呈无气状态，同时又不能提掉对方的棋子，这个点就叫该方的"禁着点"。禁着点不能落子。但如果下子后虽然自己没气了，却能提掉对方的棋子，那就不是禁着点，可以下。',
    analogy: '就像有些门是锁着的不能进，但如果进了门能把敌人赶走，那就可以进！',
    tip: '判断禁着点的关键是：下子后自己无气且不能提子 = 禁着。',
  },
  {
    id: 'jie',
    term: '劫',
    reading: 'jié',
    category: 'special',
    categoryLabel: '特殊规则',
    difficulty: 2,
    shortDesc: '双方反复互提一子的特殊局面，有特殊规则限制',
    fullDesc: '当一方提掉对方一颗子后，对方如果在同一位置立即回提，就又恢复到原来的局面，如此循环永无止境。围棋规则规定：打劫时，被提子一方不能立即回提，必须先在其他地方下一手（找"劫材"），等对方应一手后，才能回提。这就叫"劫"或"打劫"。',
    analogy: '就像两个小朋友抢一个玩具，你抢过来我又抢回去……所以规定：抢到后对方不能马上抢，要先去做别的事再来抢！',
    tip: '打劫时要找"劫材"——就是在别处下一手让对方不得不应的地方。劫材多的一方打劫有利。',
  },
  {
    id: 'mu',
    term: '目',
    reading: 'mù',
    category: 'basic',
    categoryLabel: '基础概念',
    difficulty: 1,
    shortDesc: '被一方棋子围住的空交叉点',
    fullDesc: '棋盘上，被一方棋子完全围住的空白交叉点，称为"目"。目是计算胜负的基本单位，每个空交叉点算1目。围住越多的目，赢面越大。',
    analogy: '目就像你圈起来的地盘，每个空位算一块地。',
    tip: '围棋最终比的就是谁围的目多，记住这个终极目标！',
  },

  // ===== 吃子手法 =====
  {
    id: 'shuangdachi',
    term: '双打吃',
    reading: 'shuāng dǎ chī',
    category: 'capture',
    categoryLabel: '吃子手法',
    difficulty: 1,
    shortDesc: '一子落下，同时打吃对方两处棋子',
    fullDesc: '落下一颗棋子，同时使对方的两个棋子或两组棋子都只剩一口气，就叫"双打吃"。对方无法同时救两处，必然损失一方。这是非常有效的攻击手段。',
    analogy: '就像一石二鸟，你一下打中了两只鸟，对方只能救一只！',
    tip: '寻找对方两块棋共享的断点，是发现双打吃机会的关键。',
  },
  {
    id: 'guanmenchi',
    term: '关门吃',
    reading: 'guān mén chī',
    category: 'capture',
    categoryLabel: '吃子手法',
    difficulty: 1,
    shortDesc: '像关门一样把对方的棋子关在里面吃掉',
    fullDesc: '找到对方的断点，在断点处落子，像关门一样把对方棋子封在里面，使其无法逃脱，就叫"关门吃"。关门吃的关键是切断对方棋子与外部援兵的联系。',
    analogy: '就像把小偷关在房间里，他跑不掉了！',
    tip: '关门吃要先找到断点，断点就是那扇"门"。',
  },
  {
    id: 'baochi',
    term: '抱吃',
    reading: 'bào chī',
    category: 'capture',
    categoryLabel: '吃子手法',
    difficulty: 1,
    shortDesc: '把对方棋子往自己棋子多的方向赶，像拥抱一样围住',
    fullDesc: '把对方的棋子往自己棋子多的方向赶过去，利用己方棋子的力量像怀抱一样将对方围住吃掉，叫作"抱吃"。抱吃和关门吃手法类似，关键是切断对方逃跑路线。',
    analogy: '就像好多小朋友手拉手围成圈，把对方圈在中间出不去！',
    tip: '打吃时，要把对方赶向自己人多的一边，而不是让对方逃向空旷处。',
  },
  {
    id: 'zhengzi',
    term: '征子',
    reading: 'zhēng zǐ',
    category: 'capture',
    categoryLabel: '吃子手法',
    difficulty: 2,
    shortDesc: '从两边连续打吃，像扭羊头一样一路追到底',
    fullDesc: '从两边连续打吃对方棋子，使其始终只有一口气，无法逃脱，直到被逼到棋盘边缘提掉，这种吃子方法叫"征子"，俗称"扭羊头"。征子前要确认"征子有利"——即在征子路线上没有对方接应的棋子，否则征子会失败，反而自己露出破绽。',
    analogy: '就像赶羊一样，从两边轮着赶，羊只能沿着一条路跑到死胡同！判断征子能否成功，口诀是"能否征子看六线"。',
    tip: '征子前一定要检查路线上是否有对方棋子接应，否则可能被反杀！',
  },
  {
    id: 'jiachi',
    term: '枷吃',
    reading: 'jiā chī',
    category: 'capture',
    categoryLabel: '吃子手法',
    difficulty: 2,
    shortDesc: '像枷锁一样从外面把对方棋子锁住',
    fullDesc: '当对方棋子距离较远，无法直接征吃时，用一颗棋子形成"枷"的形状，从外面封锁对方所有逃跑路线，叫作"枷吃"。枷吃是征子的替代方案，当征子不利时可以考虑枷吃。',
    analogy: '就像给对方套上枷锁，虽然不直接接触，但四面八方都逃不掉！',
    tip: '征子不利时，想想能不能枷吃。枷吃比征子更稳健，不受远方棋子影响。',
  },
  {
    id: 'pu',
    term: '扑',
    reading: 'pū',
    category: 'capture',
    categoryLabel: '吃子手法',
    difficulty: 2,
    shortDesc: '故意送吃一子，设陷阱吃掉对方更多棋子',
    fullDesc: '"扑"是故意在对方虎口里送一颗棋子，让对方提掉后，反而使得对方棋子的气变少或产生断点，从而吃掉对方更多的棋子。扑是"弃子战术"的经典手法，含"置之死地而后生"之意。扑之后接"倒扑"可以直接提回，接"接不归"可以切断对方。',
    analogy: '就像钓鱼，先放鱼饵（送一子），等鱼上钩后一网打尽！',
    tip: '扑的关键是送吃之后必须有后续手段，不能白白送子。',
  },
  {
    id: 'daopu',
    term: '倒扑',
    reading: 'dào pū',
    category: 'capture',
    categoryLabel: '吃子手法',
    difficulty: 2,
    shortDesc: '送吃一子后，对方提子反而让自己被整体吃掉',
    fullDesc: '倒扑是扑的延伸手法：先送吃一子，对方提子后，该位置变成空点，己方再在此处落子，可以一次性提掉对方更多的棋子。对方提子后反而陷入更大的困境。',
    analogy: '就像特洛伊木马，对方以为占了便宜拿走了，其实里面藏着陷阱！',
    tip: '倒扑的关键是计算提子后的局面，确认对方提子后己方能反吃。',
  },
  {
    id: 'jiebugui',
    term: '接不归',
    reading: 'jiē bù guī',
    category: 'capture',
    categoryLabel: '吃子手法',
    difficulty: 2,
    shortDesc: '让对方棋子看似能连接回去，实际接上反被吃更多',
    fullDesc: '通过连续打吃，把对方棋子往其本阵赶，对方看似能通过连接逃回，但连接后反而连带更多棋子一起被吃，叫"接不归"。这就像追击时设下伏兵，对方逃回本阵时反而被一网打尽。',
    analogy: '就像捉迷藏，对方以为跑回家就安全了，结果家里也藏着你的队友！',
    tip: '接不归常利用扑的手法制造断点，追击时要注意对方连接后的气数。',
  },

  // ===== 棋形与眼 =====
  {
    id: 'yan',
    term: '眼',
    reading: 'yǎn',
    category: 'shape',
    categoryLabel: '棋形与眼',
    difficulty: 2,
    shortDesc: '由己方棋子围住的空交叉点，棋子存活的保障',
    fullDesc: '由几个连接在一起的己方棋子围住的一个或两个空交叉点，称为"眼"。眼是棋子存活的关键条件。一块棋如果有两个真眼，就是"活棋"，对方永远无法吃掉。',
    analogy: '眼就像棋子的"安全屋"，有了两个安全屋，棋子就永远安全了！',
    tip: '做眼是防守的核心，一块棋需要两个真眼才能活。',
  },
  {
    id: 'zhenyan',
    term: '真眼',
    reading: 'zhēn yǎn',
    category: 'shape',
    categoryLabel: '棋形与眼',
    difficulty: 2,
    shortDesc: '完全由己方棋子围住的眼，对方无法破坏',
    fullDesc: '由己方连接完整的棋子围成的眼，对方无法通过在眼内落子来破坏，叫作"真眼"。真眼的判定条件是：围住空点的所有棋子都是己方的，且彼此连接。两个真眼是活棋的充分必要条件。',
    analogy: '真眼就像坚固的城堡，城墙完整无缺，敌人进不来！',
    tip: '注意检查围眼的棋子是否有断点，有断点的可能是假眼。',
  },
  {
    id: 'jiayan',
    term: '假眼',
    reading: 'jiǎ yǎn',
    category: 'shape',
    categoryLabel: '棋形与眼',
    difficulty: 2,
    shortDesc: '看似是眼但实际不完整，对方可以破坏',
    fullDesc: '由己方棋子围成的类似眼的形状，但棋子之间有断点或未完全连接，对方可以在适当时候落子破坏这个眼，叫作"假眼"。假眼不能算作活棋条件，有假眼的棋块仍可能是死棋。',
    analogy: '假眼就像豆腐渣工程，看起来是城堡，但城墙有裂缝，敌人一推就塌！',
    tip: '做眼时要确保棋子完全连接，避免做出假眼。',
  },
  {
    id: 'huoqi',
    term: '活棋',
    reading: 'huó qí',
    category: 'shape',
    categoryLabel: '棋形与眼',
    difficulty: 2,
    shortDesc: '有至少两个真眼的棋，永远不会被提走',
    fullDesc: '棋盘上凡是对方无法提取的棋就是活棋。活棋通常具备两只真眼，对方填一只眼时，另一只眼仍保持气，对方无法同时在两只眼里落子，因此永远无法提走整块棋。',
    analogy: '有两个安全出口的房子，堵住一个门还有另一个门，永远能跑出去！',
    tip: '确保自己的重要棋块做出两只真眼，是围棋的基本生存法则。',
  },
  {
    id: 'siqi',
    term: '死棋',
    reading: 'sǐ qí',
    category: 'shape',
    categoryLabel: '棋形与眼',
    difficulty: 2,
    shortDesc: '无法做出两个真眼的棋，最终会被提走',
    fullDesc: '棋盘上迟早能被对方提取的棋就是死棋。死棋不具有两只真眼，或者空间不足以做出两只真眼。死棋即使暂时还在棋盘上，最终也会被对方吃掉。',
    analogy: '没有安全出口的房子，迟早会被敌人攻破！',
    tip: '判断死活是围棋最重要的基本功之一，需要大量练习死活题。',
  },
  {
    id: 'shuanghuo',
    term: '双活',
    reading: 'shuāng huó',
    category: 'shape',
    categoryLabel: '棋形与眼',
    difficulty: 3,
    shortDesc: '双方互围的棋都没有两只眼，但谁也吃不了谁',
    fullDesc: '双方互围的棋子均无两只真眼，但又都不能制杀对方，这种局面叫"双活"，也称"公活"。双活时双方共享"公气"（双方棋子之间的空点），谁先填公气谁先被吃，因此双方都不填，最终这些棋子都算活棋。',
    analogy: '就像两个人互相掐住对方脖子，谁先松手谁就被掐，所以谁也不敢动！',
    tip: '双活是一种特殊的活棋形式，注意公气的计算。',
  },
  {
    id: 'haoxing',
    term: '好形',
    reading: 'hǎo xíng',
    category: 'shape',
    categoryLabel: '棋形与眼',
    difficulty: 2,
    shortDesc: '效率高、结构紧凑的棋子形状',
    fullDesc: '棋子的排列效率高、结构紧凑、没有多余或薄弱之处的棋形叫"好形"。常见的好形包括：跳、飞、尖、拆等。好形的棋子配合紧密，既便于围空又便于战斗。',
    analogy: '好形就像士兵排成整齐的方阵，力量集中、行动高效！',
    tip: '下棋时追求好形，避免愚形（效率低下的棋形）。',
  },
  {
    id: 'yuxing',
    term: '愚形',
    reading: 'yú xíng',
    category: 'shape',
    categoryLabel: '棋形与眼',
    difficulty: 2,
    shortDesc: '效率低下的棋子形状，又称"坏形"',
    fullDesc: '棋子堆叠在一起，效率低下的棋形叫"愚形"或"坏形"。典型的愚形有空三角（三颗棋子形成三角形但中间空了一个点）。愚形子力重复，既围不到空又缺乏战斗力。',
    analogy: '愚形就像所有人挤在一个角落，既干不了活又浪费人力！',
    tip: '尽量避免走出愚形，每颗棋子都应该发挥最大的效率。',

  // ===== 布局要领 =====
  },
  {
    id: 'jinjiao',
    term: '金角银边草肚皮',
    reading: '',
    category: 'layout',
    categoryLabel: '布局要领',
    difficulty: 1,
    shortDesc: '角最容易围空，边次之，中间最难',
    fullDesc: '这是围棋最重要的布局格言。在角部，只需两面棋子就能围住地盘；在边上，需要三面；在中腹，四面都需要。因此角部围空效率最高（金角），边部次之（银边），中腹效率最低（草肚皮）。布局时应先占角，再占边，最后才走中腹。',
    analogy: '就像盖房子，角落只需要两面墙就能围成一个房间，边上要三面墙，中间要四面墙，当然是角落最划算！',
    tip: '开局先占角，这是围棋最重要的常识。',
  },
  {
    id: 'xingwei',
    term: '星',
    reading: 'xīng wèi',
    category: 'layout',
    categoryLabel: '布局要领',
    difficulty: 1,
    shortDesc: '棋盘上的圆点标记，在四四位置',
    fullDesc: '星位是棋盘上用圆点标记的交叉点，位于第四线和第四线的交叉处（四四）。19路棋盘有9个星位（四角+四边+天元），9路棋盘有5个。星位占角速度快，一手棋就控制了角部，但守角稍弱，对方可以在三三侵入。星位布局侧重发展外势。',
    analogy: '星位就像战场上的制高点，站上去就能控制一大片区域！',
    tip: '星位是初学者最容易理解的占角方式，先学会星位开局。',
  },
  {
    id: 'xiaomu',
    term: '小目',
    reading: 'xiǎo mù',
    category: 'layout',
    categoryLabel: '布局要领',
    difficulty: 2,
    shortDesc: '三四线交叉点，兼顾实地和外势的平衡占角',
    fullDesc: '小目是棋盘上第三线和第四线交叉的位置，每个角有两个小目。小目兼有三线（实利线）的实地和四线（势力线）的外势，是最平衡的占角方式。小目占角后可根据对方挂角选择取地或取势，变化丰富，是职业棋手最常用的占角方式。',
    analogy: '小目就像文武双全的将军，既能守地盘又能向外扩张！',
    tip: '小目定式数量最多，初学时先掌握1-2种基本定式即可。',
  },
  {
    id: 'sansan',
    term: '三三',
    reading: 'sān sān',
    category: 'layout',
    categoryLabel: '布局要领',
    difficulty: 2,
    shortDesc: '三三线交叉点，一手保角，重视实地',
    fullDesc: '三三是棋盘上第三线和第三线交叉的位置，每个角有一个。三三占角一手棋就牢牢控制角部实地，对方无法侵入。但三三位置较低，对外势发展不利，容易被对方封住。在现代围棋中，三三占角一度被认为位置太低，但近年来AI重新重视了三三的价值。',
    analogy: '三三就像挖了一个深地堡，很安全但看不到远处的风景。',
    tip: '三三守角最稳，但要注意发展外势来弥补高度不足。',
  },
  {
    id: 'guajiao',
    term: '挂角',
    reading: 'guà jiǎo',
    category: 'layout',
    categoryLabel: '布局要领',
    difficulty: 2,
    shortDesc: '对方占角后，在角附近下子来争夺角部',
    fullDesc: '当一方已经占角后，另一方在角的附近下子，以达到分占角部利益或攻击对方角部的目的，叫"挂角"。常见的挂角方式有小飞挂角、大飞挂角、一间高挂等。挂角后通常会引发定式，形成角部的攻防。',
    analogy: '就像对方建了城堡，你在城堡旁边也建一个据点，分一杯羹！',
    tip: '挂角是布局阶段最常见的接触方式，要学习常见的挂角应对。',
  },
  {
    id: 'dijiao',
    term: '守角',
    reading: 'dì jiǎo',
    category: 'layout',
    categoryLabel: '布局要领',
    difficulty: 2,
    shortDesc: '占角后再补一手，巩固角部地盘',
    fullDesc: '占角后，再花一手棋来巩固角部的地盘，叫"守角"或"缔角"。常见的守角方式有无忧角（小目+三三方向飞）、大飞守角、小飞守角等。守角使角部更加牢固，但也花了一手棋的代价。',
    analogy: '就像占了一块地后，再围一道围墙把它圈起来。',
    tip: '守角和挂角是布局中攻防的一对矛盾，要权衡守角和抢占大场的时机。',
  },
  {
    id: 'chaibian',
    term: '拆边',
    reading: 'chāi biān',
    category: 'layout',
    categoryLabel: '布局要领',
    difficulty: 2,
    shortDesc: '在边上间隔一定距离落子，建立边上的势力',
    fullDesc: '在边上，以己方棋子为基准，间隔一定距离（通常是二间或三间）落子，建立边上的势力范围，叫"拆边"或"拆"。拆边的距离要根据棋子的位置和全局形势来决定，拆得太大容易被对方打入，拆得太小效率不高。',
    analogy: '就像盖房子时的间距规划，隔太近太挤，隔太远管不过来。',
    tip: '开局占角后就要考虑拆边，把角上的优势扩展到边上。',
  },
  {
    id: 'dingshi',
    term: '定式',
    reading: 'dìng shì',
    category: 'layout',
    categoryLabel: '布局要领',
    difficulty: 3,
    shortDesc: '角部攻防中经过验证的固定下法',
    fullDesc: '在角部，一方占角后另一方挂角，双方按照一定的行棋次序进行攻防，最终形成双方大体安定、利益均等的基本棋形，这些经过长期验证的固定下法叫"定式"。定式的种类很多，常见的有星定式、小目定式、三三定式等。学习定式是提高布局水平的重要途径。',
    analogy: '定式就像武术中的套路，前人总结好的最佳攻防招式，学会了就能应付各种情况！',
    tip: '初学者先学2-3种基本定式，不要贪多。理解定式背后的道理比死记硬背更重要。',
  },

  // ===== 中盘战斗 =====
  {
    id: 'houshi',
    term: '厚势',
    reading: 'hòu shì',
    category: 'middlegame',
    categoryLabel: '中盘战斗',
    difficulty: 3,
    shortDesc: '己方强大的外力，虽然未围实地但有巨大潜力',
    fullDesc: '一块棋子朝向开阔方向排列，虽然尚未围成实际地盘，但具有很强的战斗力和发展潜力，叫"厚势"或"外势"。厚势可以用来攻击对方、围大模样或形成立体结构。棋谚云"不要用厚势围地"，厚势的最佳用法是攻击而非围空。',
    analogy: '厚势就像一支强大的军队列阵在外，虽然还没占地盘，但敌人不敢靠近！',
    tip: '有了厚势要主动攻击或围大模样，不要用厚势去守小空，那太浪费了。',
  },
  {
    id: 'shili',
    term: '实利',
    reading: 'shí lì',
    category: 'middlegame',
    categoryLabel: '中盘战斗',
    difficulty: 3,
    shortDesc: '已经确定的实地，是看得见摸得着的成果',
    fullDesc: '已经围住的确切地盘，即"目"的数量，叫"实利"或"实地"。实利和厚势是围棋中的一对基本矛盾。取实地意味着拿到确定的地盘但可能放弃外势，取厚势意味着发展潜力大但地盘还不确定。',
    analogy: '实利就像口袋里已经有的钱，厚势就像未来的赚钱能力，两者都很重要！',
    tip: '实利和厚势的取舍是围棋的核心决策之一，要全局判断。',
  },
  {
    id: 'xianshou',
    term: '先手',
    reading: 'xiān shǒu',
    category: 'middlegame',
    categoryLabel: '中盘战斗',
    difficulty: 2,
    shortDesc: '下完这步对方必须应，自己掌握主动权',
    fullDesc: '落下一子后，对方不得不应一手来应对的着法，叫"先手"。先手意味着你掌握了行棋的主动权，对方被迫跟随你的节奏。围棋中非常讲究先手，"先手为王"是重要原则。与先手相对的是"后手"——对方不必立刻应对的着法。',
    analogy: '先手就像打乒乓球时主动进攻，对方只能被动防守！',
    tip: '争取先手、保持先手，是围棋行棋的黄金法则。',
  },
  {
    id: 'daru',
    term: '打入',
    reading: 'dǎ rù',
    category: 'middlegame',
    categoryLabel: '中盘战斗',
    difficulty: 3,
    shortDesc: '深入对方势力范围，破坏对方围空',
    fullDesc: '在对方已经围成或正在围的地盘中落子，破坏对方的围空计划，叫"打入"。打入是中盘战斗的重要手段，成功的打入可以大幅度削弱对方的势力。但打入也有风险，如果被对方攻击，打入的棋子可能被吃掉。',
    analogy: '打入就像派特种兵深入敌人后方，破坏他们的基地！但要注意安全撤退的路线。',
    tip: '打入前要计算好逃跑路线和做活的可能性，不要盲目打入。',
  },
  {
    id: 'tengnao',
    term: '腾挪',
    reading: 'téng nuó',
    category: 'middlegame',
    categoryLabel: '中盘战斗',
    difficulty: 3,
    shortDesc: '灵活转身，在对方势力范围内巧妙处理弱棋',
    fullDesc: '当己方棋子在对方势力范围内处于不利地位时，通过弃子、转身、借用等手段灵活处理，不与对方硬拼，而是寻找其他获利的机会，这种灵活处理的手法叫"腾挪"。腾挪是围棋中最高级的战术之一。',
    analogy: '腾挪就像柔道，用对方的力量反击对方，四两拨千斤！',
    tip: '弱棋不要硬跑，考虑弃子转身，在其他地方获得补偿。',
  },
  {
    id: 'qizi',
    term: '弃子',
    reading: 'qì zǐ',
    category: 'middlegame',
    categoryLabel: '中盘战斗',
    difficulty: 3,
    shortDesc: '主动放弃一些棋子，换取更大的利益',
    fullDesc: '有意识地放弃一些棋子，以换取在别处更大的利益，叫"弃子"。弃子是围棋中的高级战术，看似吃亏实则占便宜。通过弃子可以获取先手、形成厚势、制造攻击目标等。很多手筋（如扑、倒扑）都建立在弃子的基础上。',
    analogy: '弃子就像下棋中的"舍车保帅"，牺牲小部队换取全局胜利！',
    tip: '不要每颗棋子都舍不得放弃，要算总账，看全局利益。',
  },

  // ===== 官子收官 =====
  {
    id: 'guanzi',
    term: '官子',
    reading: 'guān zǐ',
    category: 'endgame',
    categoryLabel: '官子收官',
    difficulty: 2,
    shortDesc: '棋局末尾确定边界的着法',
    fullDesc: '中盘战斗基本结束后，双方所占地域大致确定，进而通过一系列着法使双方属地完全明确，这个阶段叫"官子"或"收官"。官子阶段虽然不如中盘战斗激烈，但经常决定胜负。官子的大小和先后手是收官的关键。',
    analogy: '官子就像画完画后修整边缘，虽然不是创作主体，但决定最终效果！',
    tip: '官子阶段要仔细计算每手棋的价值，先抢大官子。',
  },
  {
    id: 'xianshouguanzi',
    term: '先手官子',
    reading: 'xiān shǒu guān zǐ',
    category: 'endgame',
    categoryLabel: '官子收官',
    difficulty: 3,
    shortDesc: '收官时对方必须应对的官子，价值加倍',
    fullDesc: '在官子阶段，落子后对方不得不应，自己还能继续抢占其他官子的着法，叫"先手官子"。先手官子的实际价值约为后手官子的两倍，因为先手官子不仅自己得利，还能保持行棋的主动权继续获利。',
    analogy: '先手官子就像免费的好东西，拿了还能继续拿别的！',
    tip: '收官时优先抢占先手官子，这是收官的基本原则。',
  },

  // ===== 特殊 =====
  {
    id: 'tianyuan',
    term: '天元',
    reading: 'tiān yuán',
    category: 'special',
    categoryLabel: '特殊规则',
    difficulty: 1,
    shortDesc: '棋盘正中心的星位',
    fullDesc: '棋盘正中心的交叉点称为"天元"，是棋盘上唯一一个四面对称的点。天元在布局中很少直接占据，因为中腹围空效率低。但在某些特殊布局中，天元可以作为呼应全局的战略要点。天元也是棋盘上最重要的参考点。',
    analogy: '天元就像地球的赤道中心点，是整个棋盘的"心脏"位置！',
    tip: '开局一般不直接占天元，但中盘战斗时天元可能是关键的行棋方向。',
  },
  {
    id: 'shoujin',
    term: '手筋',
    reading: 'shǒu jīn',
    category: 'special',
    categoryLabel: '特殊规则',
    difficulty: 3,
    shortDesc: '局部战斗中精妙的着手，是围棋的"妙手"',
    fullDesc: '手筋是围棋中指在局部战斗中发挥奇效的精妙着手。手筋不是普通的下法，而是通过巧妙的计算，在看似不利的情况下找到最佳的攻击或防守手段。吃子手筋包括征子、枷吃、倒扑、接不归等，攻防手筋包括靠、扳、点、跨等。',
    analogy: '手筋就像武术中的绝招，看似简单但效果惊人！一招制敌！',
    tip: '多练习手筋题是提高棋力的最有效方法之一。',
  },
  {
    id: 'jianhe',
    term: '见合',
    reading: 'jiàn hé',
    category: 'special',
    categoryLabel: '特殊规则',
    difficulty: 3,
    shortDesc: '两个好点必得其一的态势',
    fullDesc: '棋盘上存在两个价值相当的好点，一方占了其中一个，另一方就能占另一个，这种双方各得其一的态势叫"见合"。见合是围棋中判断形势和选择行棋方向的重要概念。在布局和中盘中，利用见合的原理可以确保自己总能获得一定的利益。',
    analogy: '就像自助餐两道好菜，你选了一个，另一个归对手，但怎么选都不亏！',
    tip: '创造见合的局面，让自己怎么走都有收获。',
  },
];

// 按难度筛选
export function getTermsByDifficulty(level: 1 | 2 | 3): GoTerm[] {
  return GO_TERMS.filter(t => t.difficulty === level);
}

// 按分类筛选
export function getTermsByCategory(category: GoTerm['category']): GoTerm[] {
  return GO_TERMS.filter(t => t.category === category);
}

// 搜索术语
export function searchTerms(query: string): GoTerm[] {
  const q = query.toLowerCase();
  return GO_TERMS.filter(t =>
    t.term.includes(q) ||
    (t.reading && t.reading.includes(q)) ||
    t.shortDesc.includes(q) ||
    t.fullDesc.includes(q)
  );
}

// 获取所有术语ID列表（供AI解说参考）
export function getAllTermNames(): string[] {
  return GO_TERMS.map(t => t.term);
}
